name: Build and push

on:
  push:
    branches: '**'
    tags: 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Git metadata
        id: git
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
          echo "commit_date=$(git log -1 --format=%cd --date=format:'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rofleksey
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: rofleksey/nicemaxxingbot:latest
          build-args: |
            GIT_TAG=${{ steps.git.outputs.tag }}
            GIT_COMMIT=${{ steps.git.outputs.sha }}
            GIT_COMMIT_DATE=${{ steps.git.outputs.commit_date }}
